# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['reddit_spier.py'],  # 主脚本文件
    pathex=[],
    binaries=[],
    datas=[],  # 可以在这里添加额外的数据文件
    hiddenimports=[
        'pandas', 
        'praw', 
        'prawcore',
        'praw.models',
        'praw.config',
        'praw.exceptions',
        'praw.models.reddit.base',
        'praw.models.reddit.subreddit',
        'praw.models.reddit.submission',
        'praw.models.reddit.comment',
        'praw.models.reddit.redditor',
        'praw.models.reddit.message',
        'praw.models.reddit.trophy',
        'praw.models.reddit.mixins',
        'praw.models.listing.generator',
        'praw.models.listing.mixins',
        'praw.models.auth',
        'praw.models.util',
        'praw.models.preferences',
        'praw.models.helpers',
        'praw.models.mod',
        'praw.models.inbox',
        'praw.models.front',
        'praw.models.multireddit',
        'praw.models.subreddits',
        'praw.models.user',
        'praw.models.trophy',
        'praw.models.list',
        'praw.models.modmail',
        'praw.models.stylesheet',
        'praw.models.widgets',
        'praw.models.collection',
        'praw.models.flair',
        'praw.models.emoji',
        'praw.models.removal_reasons',
        'praw.models.rules',
        'praw.models.modaction',
        'praw.models.wikipage',
        'praw.models.wikipage',
        'praw.models.stream',
        'praw.models.redditors',
        'praw.models.live',
        'praw.models.domain',
        'praw.models.comment_forest',
        'praw.models.comment_sort',
        'praw.models.comment_replies',
        'praw.models.comment_helpers',
        'praw.models.comment_moderation',
        'praw.models.comment_submission',
        'praw.models.comment_tree',
        'praw.models.comment_util',
        'praw.models.comment_forest',
        'praw.models.comment_sort',
        'praw.models.comment_replies',
        'praw.models.comment_helpers',
        'praw.models.comment_moderation',
        'praw.models.comment_submission',
        'praw.models.comment_tree',
        'praw.models.comment_util',
    ],  # 确保包含所有必要的隐藏导入
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(
    a.pure, 
    a.zipped_data,
    cipher=block_cipher
)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Reddit关键词采集工具',  # 可执行文件名称
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # 临时设置为True以便查看错误信息
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
) 